---
title: "Planejamento e Análise de ensaios Agronômicos"
subtitle: "Capaciação Interna - NEPEM"
author: "Prof. Dr. Tiago Olivoto"
date: today
format: 
  html:
    theme: cosmo        # pode trocar: cosmo, journal, flatly, united, etc
    toc: true           # ativa sumário
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: true     # código dobrável
    code-tools: true    # botão de copiar código
    df-print: paged
    page-layout: article
    fontsize: 14pt
    linestretch: 1.5
    smooth-scroll: true
    title-block-banner: "#00FF99"  # cor do banner do título
    title-block-style: default
    title-block-banner-color: white
    mainfont: "Arial"
    monofont: "Fira Code"
---

# Pacotes


```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(Rcpp)
library(FielDHub)
library(qrlabelr)
library(uuid)
library(cli)
```

# Funções auxiliares
```{r}
source("funcoes_planejamento.R")
```


# Unifatorial
## Caderno de campo

## Etiquetas


```{r}
# qrlabelr::gp_label(dat = as.data.frame(croqui$fieldbook),
#                    # Top left 1
#                    top_left_txt1 = 'Dose:',
#                    top_left_id1 = 'TREATMENT',
#                    # Top left 2
#                    top_left_txt2 = 'Rep:',
#                    top_left_id2 = 'REP',
#                    # Top right 1
#                    # top_right_txt1 = 'Rep:',
#                    # top_right_id1 = 'REP',
#                    # Top right 2
#                    # top_right_txt2 = 'Rep:',
#                    # top_right_id2 = 'REP',
#                    # Bottom left 1
#                    bottom_left_txt1 = "UUID:",
#                    bottom_left_id1 = "UNIQUE_ID",
#                    # Bottom left 2
#                    # bottom_left_txt2 = "Trt:",
#                    # bottom_left_id2 = "TRT_COMB",
#                    # Center 1
#                    center_right_txt1 = "Vaso:",
#                    center_right_id1 = "PLOT",
#                    # Center 2
#                    center_right_txt2 = "Protocolo:",
#                    center_right_id2 = "LOCATION",
#                    # Center 3
#                    # center_right_txt3 = "Col",
#                    # center_right_id3 = "COLUMN",
#                    filename = "test.pdf",
#                    # Page size
#                    page_wdt = 8.27,
#                    page_hgt = 11.72,
#                    top_mar = 0,
#                    bot_mar = 0,
#                    left_mar = 0.25,
#                    right_mar = 0.25,
#                    # Layout
#                    numrow = 9,
#                    numcol = 3,
#                    font_sz = 10,
#                    rname = "Olivoto",
#                    get_unique_id = "custom",
#                    unique_id =  "UNIQUE_ID",
#                    family = "sans")
```


# Fatorial

## Caderno de campo

## Etiquetas


